---
title: "Exploring the Legacy of Redlining in California with Open Data & Open Source Tools"
author: "David Altare<br><span style = 'font-size: 60%; line-height: 130%; display: block;'>California Environmental Protection Agency (CalEPA)<br>State Water Resources Control Board<br>Office of Information Management & Analysis (OIMA)</span>"
date: 'Water Data Seminar Series | March 18, 2021<br><br>`r icons::fontawesome("link")` [bit.ly/redline-03-18](https://bit.ly/redline-03-18)'

output:
  xaringan::moon_reader:
    self_contained: true
    lib_dir: libs
    chakra: libs/remark-latest.min.js
    css: [xaringan-themer.css, my-theme.css]
    nature:
      slideNumberFormat: "%current%"
      titleSlideClass: ["left", "middle", "inverse"]
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: false
    includes: 
      in_header: "in_header.html" # see: https://github.com/fnaufel/smartify
      after_body: "after_body.html" # see same source as above
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  fig.show = TRUE,
  hiline = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
# style_duo_accent(
#   primary_color = "#1381B0",
#   secondary_color = "#FF961C",
#   inverse_header_color = "#FFFFFF"
# )

style_mono_light(base_color = "#125972", 
                 code_highlight_color = "#c0e8f5",
                 link_color = "#197b9e",
                 title_slide_background_image = 'images/data_center_logo_withText_crop_resize.png',
                 title_slide_background_size = '400px',
                 title_slide_background_position = '95% 95%')
```

```{r xaringan-logo, echo=FALSE}
xaringanExtra::use_tile_view()

xaringanExtra::use_logo(
  image_url = "images/data_center_logo_withText_crop_resize.png",
  width = "280px",
  height = "68px",
  link_url = 'https://github.com/CAWaterBoardDataCenter'
)
```

## Slide 1

### Header

Text 

---
class: inverse center middle

# Topic Changing Slide

---

## Slide 2

- Bullet 1
    - Sub-Bullet 1

- Bullet 2

---
class: center, middle

# Thanks!
